import React, { useState, useEffect } from 'react';
import { BrainCircuit, TrendingUp, DollarSign, MessageSquare, PieChart, Sparkles, Filter } from 'lucide-react';
import Navbar from '../components/Navbar';
import api from '../services/api';
import '../styles/intelligence.css';

const Intelligence = () => {
  const [jobs, setJobs] = useState([]);
  const [selectedJobId, setSelectedJobId] = useState('');
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const loadJobs = async () => {
      try {
        const res = await api.get('/jobs');
        const list = res.data || [];
        setJobs(list);
        if (list.length > 0) {
          setSelectedJobId(list[0].id);
        }
      } catch (err) {
        console.error(err);
      }
    };
    loadJobs();
  }, []);

  useEffect(() => {
    if (!selectedJobId) return;
    const fetchIntel = async () => {
      setLoading(true);
      try {
        const res = await api.get(`/data/intelligence/${selectedJobId}`);
        setReports(res.data || []);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchIntel();
  }, [selectedJobId]);

  const activeReport = reports[0] || null;

  return (
    <div className="main-content">
      <Navbar title="Intelligence & Market Analytics" />
      <div className="page-wrapper">
        
        {/* Selector Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
          <div>
            <h2 className="section-title">Automated Data Synthesis & Market Insights</h2>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
              Synthesized pricing metrics, NLP sentiment polarity, and entity graphs generated by Celery AI post-processors
            </p>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <Filter size={18} color="var(--text-muted)" />
            <select 
              value={selectedJobId} 
              onChange={(e) => setSelectedJobId(e.target.value)}
              style={{ minWidth: '220px' }}
            >
              {jobs.map((j) => (
                <option key={j.id} value={j.id}>{j.name} ({j.crawler_type})</option>
              ))}
            </select>
          </div>
        </div>

        {/* Intelligence Content */}
        {!activeReport ? (
          <div className="panel-card" style={{ marginTop: '2rem', textAlign: 'center', padding: '3rem' }}>
            <BrainCircuit size={48} color="var(--accent-primary)" style={{ margin: '0 auto 1rem' }} />
            <h3>Generating Intelligence Report...</h3>
            <p style={{ color: 'var(--text-secondary)', marginTop: '6px' }}>
              Once your crawl job finishes ingesting items, the AI intelligence post-processor will produce automated pricing, sentiment, and entity breakdowns here.
            </p>
          </div>
        ) : (
          <div className="intel-insights-grid">
            
            {/* Primary Analysis */}
            <div className="intel-card">
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <Sparkles size={22} color="var(--accent-primary)" />
                <h3 style={{ fontSize: '1.2rem', fontWeight: 700 }}>Executive Synthesis</h3>
              </div>

              <div style={{ 
                background: 'rgba(99, 102, 241, 0.08)', 
                border: '1px solid rgba(99, 102, 241, 0.2)',
                padding: '1.25rem',
                borderRadius: 'var(--radius-sm)',
                lineHeight: 1.6,
                color: '#e0e7ff'
              }}>
                {activeReport.summary_text}
              </div>

              {/* Pricing Intelligence Widget if available */}
              {activeReport.metrics?.pricing_intelligence && (
                <div style={{ marginTop: '1rem' }}>
                  <h4 style={{ fontSize: '0.95rem', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <DollarSign size={18} color="var(--accent-success)" />
                    <span>Pricing Spectrum & Market Averages</span>
                  </h4>
                  <div className="dashboard-grid" style={{ marginBottom: 0 }}>
                    <div className="stat-card" style={{ padding: '1rem' }}>
                      <div className="stat-info">
                        <span className="stat-label">Average Unit Price</span>
                        <span className="stat-value" style={{ fontSize: '1.3rem' }}>
                          ${activeReport.metrics.pricing_intelligence.average_price}
                        </span>
                      </div>
                    </div>
                    <div className="stat-card" style={{ padding: '1rem' }}>
                      <div className="stat-info">
                        <span className="stat-label">Min - Max Range</span>
                        <span className="stat-value" style={{ fontSize: '1.3rem' }}>
                          ${activeReport.metrics.pricing_intelligence.min_price} - ${activeReport.metrics.pricing_intelligence.max_price}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* News / Sentiment Widget if available */}
              {activeReport.metrics?.news_intelligence && (
                <div style={{ marginTop: '1rem' }}>
                  <h4 style={{ fontSize: '0.95rem', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <MessageSquare size={18} color="var(--accent-secondary)" />
                    <span>Sentiment Polarity Score</span>
                  </h4>
                  <div className="sentiment-meter">
                    <div className="sentiment-segment-pos" style={{ width: '60%' }} title="Positive" />
                    <div className="sentiment-segment-neu" style={{ width: '25%' }} title="Neutral" />
                    <div className="sentiment-segment-neg" style={{ width: '15%' }} title="Negative" />
                  </div>
                </div>
              )}
            </div>

            {/* Side breakdown */}
            <div className="intel-card">
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <PieChart size={20} color="var(--accent-secondary)" />
                <h3 style={{ fontSize: '1.1rem', fontWeight: 700 }}>Telemetry Metrics</h3>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                <div className="node-item">
                  <span>Success Ingestion Rate</span>
                  <strong style={{ color: 'var(--accent-success)' }}>
                    {activeReport.metrics.success_rate_percentage}%
                  </strong>
                </div>
                <div className="node-item">
                  <span>Avg Response Latency</span>
                  <strong>{activeReport.metrics.average_response_time_ms} ms</strong>
                </div>
                <div className="node-item">
                  <span>Analyzed Sample Records</span>
                  <strong>{activeReport.metrics.total_records_analyzed}</strong>
                </div>
              </div>

              <h4 style={{ fontSize: '0.9rem', marginTop: '1rem' }}>Discovered Key Concepts / Entities</h4>
              <div className="tag-cloud">
                {(activeReport.metrics?.news_intelligence?.top_mentioned_entities || [
                  "Distributed Crawling", "High-Throughput", "Data Extraction", "NLP Analysis", "Celery Mesh"
                ]).map((tag, idx) => (
                  <span key={idx} className="intel-tag">{tag}</span>
                ))}
              </div>
            </div>

          </div>
        )}

      </div>
    </div>
  );
};

export default Intelligence;
